###############################
#Simple morning/night triggers#
###############################
- alias: Home Assistant Start
  initial_state: False
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_bluetooth_speaker
        message: 'Home Assistant has started'

- alias: Zwave ready
  initial_state: False
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_bluetooth_speaker
        message: 'zwave network is ready'

- alias: james alert
  trigger:
    - platform: state
      entity_id: binary_sensor.mqtt_binary_sensor
      to: 'on'
  action:
    - service: notify.html5_mario_moto_z_play
      data:
        title: "Motion detected"
        message: "James is moving"
    - service: mqtt.publish
      data:
        topic: "home-assistant/camera/motion"
        payload: "OFF"

- alias: Fridge Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_fridge_door
      below: 5
  condition: 
      condition: numeric_state
      entity_id: sensor.batt_fridge_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the fridge door battery"

- alias: Garage/House Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_garage_house_door
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_garage_house_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the garage/house door battery"

- alias: Garage Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_garage_door
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_garage_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the garage door battery"

- alias: Patio door Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_patio_door
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_patio_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the patio door battery"

- alias: Hallway motion Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_guest_motion
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_guest_motion
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the hallway motion sensor battery"

- alias: Kitchen motion Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_kitchen_motion
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_kitchen_motion
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the kitchen motion battery"

- alias: Front porch motion
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.porch

- alias: Front porch off after 10min when motion off
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_off
    entity_id: switch.porch

- alias: Set up bedtime lights @22:30
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.night_light

#    - service: shell_command.foscam_location_jackie

- alias: Turn on dinner time lights
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '17:30:00'
    - platform: state
      entity_id: group.household
      to: 'home'
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '17:30:00'
      before: '20:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.dusk

- alias: Lights off when no one home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.override_home
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.dark
#    - service: shell_command.foscam_location_dining


#- alias: Turn on christmas lights at sunset
#  initial_state: True
#  hide_entity: False
#  trigger:
#    platform: sun
#    event: sunset
#  action:
#    service: homeassistant.turn_on
#    entity_id: switch.outdoor_christmas_lights_switch

#- alias: Turn off christmas lights at 9PM
#  initial_state: True
#  hide_entity: False
#  trigger:
#    platform: time
#    at: '21:00:00'
#  action:
#    service: homeassistant.turn_off
#    entity_id: switch.outdoor_christmas_lights_switch

- alias: Turn on hallway lights at motion at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.guest_motion
      to: 'motion'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_guest_hallway

- alias: Turn on kitchen lights at motion at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      to: 'motion'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_level
    - service: notify.notify
      data:
        message: "Motion seen in kitchen @ {{ now().strftime('%a %-I:%M %p') }}"

- alias: Kitchen off after 4min when motion off
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      to: 'none'
      for:
        minutes: 4
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_off
    entity_id: light.kitchen_level

- alias: Turn on master hallway when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.garage_house_door_alarm_level
    to: '255'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_master_hallway

- alias: Turn on patio when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.patio_door
    to: 'open'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_patio 

- alias: Notify if fridge open too long
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.fridge_door
    to: 'open'
    for:
      minutes: 4
  action:
    service: notify.notify
    data:
      message: "Fridge left open!"

- alias: Notify if garage open too long
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.garage_door
    to: 'open'
    for:
      minutes: 5
  action:
    service: notify.notify
    data:
      message: "Garage door left open!"

- alias: Turn on garage lights when door is opened
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.garage_door
      to: 'open'
    - platform: state
      entity_id: sensor.garage_house_door
      to: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage

########################################
#Trigger scene changes based upon media#
########################################
- alias: "Bedroom Roku stopped"
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'idle'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        before: '08:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.dark

- alias: "Bedroom Roku no longer idle"
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.watch_tv_bedroom
