###############################
#Simple morning/night triggers#
###############################
- alias: Front porch on @sundown
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: homeassistant.turn_on
    entity_id: switch.porch
- alias: Front porch off @22:30
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    after: '22:30:00'
  action:
    service: scene.turn_on
    entity_id: switch.night_light

- alias: Activate lights @dinner
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    after: '17:50:00'
  action:
    service: scene.turn_on
    entity_id: scene.dusk

- alias: Lights off @9a
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      after '09:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.dark

#- alias: Turn on christmas lights at sunset
#  initial_state: True
#  hide_entity: False
#  trigger:
#    platform: sun
#    event: sunset
#  action:
#    service: homeassistant.turn_on
#    entity_id: switch.outdoor_christmas_lights_switch_11_0

#- alias: Turn off christmas lights at 9PM
#  initial_state: True
#  hide_entity: False
#  trigger:
#    platform: time
#    after: '21:00:00'
#  action:
#    service: homeassistant.turn_off
#    entity_id: switch.outdoor_christmas_lights_switch_11_0

- alias: Turn on hallway lights at motion at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.guest_motion
      to: 'motion'
    - platform: state
      entity_id: sensor.guest_motion
      to: 'none'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_guest_hallway

- alias: Turn on kitchen lights at motion at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      to: 'motion'
    - platform: state
      entity_id: sensor.kitchen_motion
      to: 'none'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_kitchen

- alias: Turn on master hallway when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.garage_house_door_alarm_level_18_1
    to: '255'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_master_hallway

- alias: Turn on patio when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.patio_door
    to: 'open'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_patio 

- alias: Turn on garage lights when door is opened
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.garage_door
      to: 'open'
    - platform: state
      entity_id: sensor.garage_house_door
      to: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage

########################################
#Trigger scene changes based upon media#
########################################
- alias: "Bedroom Roku stopped"
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.dark

- alias: "Bedroom Roku no longer idle"
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.watch_tv_bedroom
