- id: home_assistant_start
  alias: Home Assistant Start
  initial_state: False
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_bluetooth_speaker
        message: 'Home Assistant has started'

- id: zwave_ready
  alias: Zwave ready
  initial_state: False
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_bluetooth_speaker
        message: 'zwave network is ready'

- id: james_alert
  alias: james alert
  trigger:
    - platform: state
      entity_id: binary_sensor.mqtt_binary_sensor
      to: 'on'
  action:
    - service: notify.html5_mario_moto_z_play
      data:
        title: "Motion detected"
        message: "James is moving"
    - service: mqtt.publish
      data:
        topic: "home-assistant/camera/motion"
        payload: "OFF"

- id: fridge_low_battery
  alias: Fridge Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_fridge_door
      below: 5
  condition: 
      condition: numeric_state
      entity_id: sensor.batt_fridge_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the fridge door battery"

- id: garage_house_low_battery
  alias: Garage/House Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_garage_house_door
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_garage_house_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the garage/house door battery"

- id: garage_low_battery
  alias: Garage Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_garage_door
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_garage_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the garage door battery"

- id: patio_door_low_battery
  alias: Patio door Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_patio_door
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_patio_door
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the patio door battery"

- id: hallway_motion_low_battery
  alias: Hallway motion Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_guest_motion
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_guest_motion
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the hallway motion sensor battery"

- id: kitchen_motion_low_battery
  alias: Kitchen motion Low battery
  initial_state: True
  hide_entity: False
  trigger:
    - platform: numeric_state
      entity_id: sensor.batt_kitchen_motion
      below: 5
  condition:
      condition: numeric_state
      entity_id: sensor.batt_kitchen_motion
      above: 0
  action:
      service: notify.notify
      data:
        message: "Time to change the kitchen motion battery"

- id: front_porch_ding
  alias: Front porch doorbell
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_ding
      to: 'on'
  action:
    - service: notify.webostv
      data:
        message: "Someone is at the front door"

- id: front_porch_motion
  alias: Front porch motion
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.porch
    - service: notify.webostv
      data:
        message: "Movement detected: Front Door"

- id: front_porch_motion_off
  alias: Front porch off after 10min when motion off
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_front_door_motion
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_off
    entity_id: switch.porch

- id: activate_holidays
  alias: Turn on holiday lights @sundown
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.outdoor_christmas_lights_switch

- id: activate_bedtime_scene
  alias: Set up bedtime lights @22:30
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '22:30:00'
  action:
    - service: scene.turn_on
      entity_id: scene.night_light

#    - service: shell_command.foscam_location_jackie

- id: activate_dinner_scene
  alias: Turn on dinner time lights
  initial_state: True
  hide_entity: False
  trigger:
    - platform: time
      at: '17:30:00'
    - platform: state
      entity_id: group.household
      to: 'home'
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '17:30:00'
      before: '21:00:00'
    - condition: state
      entity_id: input_boolean.presence_detection
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.dusk

- id: activate_dark_scene
  alias: Lights off when no one home
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: group.household
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.presence_detection
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.dark
#    - service: shell_command.foscam_location_dining

- id: activate_hallway_motion
  alias: Turn on hallway lights at motion at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.guest_motion
      to: 'motion'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_guest_hallway

- id: activate_kitchen_motion
  alias: Turn on kitchen lights at motion at night
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      to: 'motion'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id: light.kitchen_level
    - service: notify.notify
      data:
        message: "Motion seen in kitchen @ {{ now().strftime('%a %-I:%M %p') }}"

- id: kitchen_motion_timer
  alias: Kitchen off after 4min when motion off
  trigger:
    - platform: state
      entity_id: sensor.kitchen_motion
      to: 'none'
      for:
        minutes: 4
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: light.turn_off
    entity_id: light.kitchen_level

- id: activate_master_hallway
  alias: Turn on master hallway when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.garage_house_door_alarm_level
    to: '255'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_master_hallway

- id: activate_patio
  alias: Turn on patio when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.patio_door
    to: 'open'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_patio 

- id: activate_office
  alias: Turn on office when door opens
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.office_door
    to: 'open'
  condition:
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.office_switch

- id: office_light_timer
  alias: Office light off after 10min when door closed
  trigger:
    - platform: state
      entity_id: sensor.office_door
      to: 'closed'
      for:
        minutes: 10
  condition:
    - condition: time
      after: '07:00:00'
      before: '23:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.office_switch

- id: notify_fridge
  alias: Notify if fridge open too long
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.fridge_door
    to: 'open'
    for:
      minutes: 4
  action:
    service: notify.notify
    data:
      message: "Fridge left open!"

- id: notify_garage
  alias: Notify if garage open too long
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: sensor.garage_door
    to: 'open'
    for:
      minutes: 5
  action:
    service: notify.notify
    data:
      message: "Garage door left open!"

- id: activate_garage_lights
  alias: Turn on garage lights when door is opened
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.garage_door
      to: 'open'
    - platform: state
      entity_id: sensor.garage_house_door
      to: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_garage

########################################
#Trigger scene changes based upon media#
########################################
- id: bedroom_roku_stopped
  alias: "Bedroom Roku stopped"
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'idle'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        before: '06:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.dark

- id: bedoom_roku_started
  alias: "Bedroom Roku no longer idle"
  trigger:
    - platform: state
      entity_id: media_player.bedroom
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.watch_tv_bedroom

- id: update_google_assistant
  alias: 'Update Google Assistant when zwave is ready'
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
   - service: google_assistant.request_sync

- id: turn_lg_tv_on
  alias: "LG TV turned on"
  trigger:
    - platform: state
      entity_id: media_player.lg_webos_smart_tv
      to: 'playing'
  condition:
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: scene.turn_on
      entity_id: scene.watch_tv_living_room

- id: turn_lg_tv_off
  alias: "LG TV turned off"
  trigger:
    - platform: state
      entity_id: media_player.lg_webos_smart_tv
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    service: light.turn_on
    entity_id: light.living_room_level
    data:
      brightness: 100
