homeassistant:
  name: Limonciello House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:

device_tracker:
  - platform: netgear
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path

notify:
  platform: html5
  gcm_api_key: !secret gcm_sender_key
  gcm_sender_id: !secret gcm_sender_id

config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

recorder:
  purge_interval: 1
  purge_keep_days: 5
  exclude:
    domains:
      - updater
    entities:
      - sun.sun
      - sensor.pws_feelslike_string
      - sensor.pws_heat_index_string
      - sensor.pws_relative_humidity
      - sensor.pws_temp_f
      - sensor.pws_weather
      - sensor.pws_wind_string

#################
#Nest thermostat#
#################
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
climate:
  - platform: nest

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.1/24
#    home_interval: 10

#device_tracker:
#  - platform: bluetooth_le_tracker

##################
#weather tracking and hand built sensors#
##################
sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather
      - temp_f
      - feelslike_string
      - relative_humidity
      - wind_string
      - heat_index_string
  - platform: template
    sensors:
      batt_fridge_door:
        friendly_name: 'Fridge Door battery'
        value_template: '{% if states.zwave.fridge_door %}
                           {{ states.zwave.fridge_door.attributes.battery_level }}
                         {% else %}
                           0
                         {% endif %}'
        unit_of_measurement: '%'
      batt_garage_house_door:
        friendly_name: 'Garage/House Door battery'
        value_template: '{% if states.zwave.garage_house_door %}
                           {{ states.zwave.garage_house_door.attributes.battery_level }}
                         {% else %}
                           0
                         {% endif %}'
        unit_of_measurement: '%'
      batt_garage_door:
        friendly_name: 'Garage door battery'
        value_template: '{% if states.zwave.garage_door %}
                           {{ states.zwave.garage_door.attributes.battery_level }}
                         {% else %}
                           0
                         {% endif %}'
        unit_of_measurement: '%'
      batt_patio_door:
        friendly_name: 'Patio Door battery'
        value_template: '{% if states.zwave.patio_door %}
                           {{ states.zwave.patio_door.attributes.battery_level }}
                         {% else %}
                           0
                         {% endif %}'
        unit_of_measurement: '%'
      batt_guest_motion:
        friendly_name: 'Hallway motion battery'
        value_template: '{% if states.zwave.hallway_motion %}
                           {{ states.zwave.hallway_motion.attributes.battery_level }}
                         {% else %}
                           0
                         {% endif %}'
        unit_of_measurement: '%'
      batt_kitchen_motion:
        friendly_name: 'Kitchen motion battery'
        value_template: '{% if states.zwave.kitchen_motion %}
                           {{ states.zwave.kitchen_motion.attributes.battery_level }}
                         {% else %}
                           0
                         {% endif %}'
        unit_of_measurement: '%'
      office_door:
        value_template: '{% if is_state("binary_sensor.office_door_sensor", "off") %}closed{% else %}open{% endif %}'
        entity_id: binary_sensor.office_door_sensor
        friendly_name: 'Office Door status'
      garage_door:
        value_template: '{% if is_state("sensor.garage_door_alarm_level", "0") %}closed{% else %}open{% endif %}'
        entity_id: sensor.garage_door_alarm_level
        friendly_name: 'Garage Door status'
      garage_house_door:
        value_template: '{% if is_state("sensor.garage_house_door_alarm_level", "0") %}closed{% else %}open{% endif %}'
        friendly_name: 'Garage/House Door status'
        entity_id: sensor.garage_house_door_alarm_level
      patio_door:
        value_template: '{% if is_state("sensor.patio_door_alarm_level", "0") %}closed{% else %}open{% endif %}'
        friendly_name: 'Patio Door status'
        entity_id: sensor.patio_door_alarm_level
      fridge_door:
        value_template: '{% if is_state("sensor.fridge_door_alarm_level", "0") %}closed{% else %}open{% endif %}'
        friendly_name: 'Fridge status'
        entity_id: sensor.fridge_door_alarm_level
      guest_motion:
        value_template: '{% if is_state("sensor.hallway_motion_alarm_level", "0") %}none{% else %}motion{% endif %}'
        friendly_name: 'Guest Hallway Motion status'
        entity_id: sensor.hallway_motion_alarm_level
      kitchen_motion:
        value_template: '{% if is_state("sensor.kitchen_motion_alarm_level", "0") %}none{% else %}motion{% endif %}'
        friendly_name: 'Kitchen Motion status'
        entity_id: sensor.kitchen_motion_alarm_level

#########
#Harmony#
#########
#remote:
#  - platform: harmony
#    name: Living Room
#    host: 192.168.1.7
#    activity: 21240104

group: !include groups.yaml


#anova:
#  mac: 5C:31:3E:5D:E6:6A

zwave:
  usb_path: /dev/ttyACM0
  config_path: /home/homeassistant/.homeassistant/config
  autoheal: false
  device_config: !include zwave_device_config.yaml
  new_entity_ids: true

#for turning on echo support to zwave stuff
emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - light
    - switch
    - fan
    - scene

scene:
  - name: Sexy time
    entities:
      switch.master_light_switch:
        state: off
      light.mario_lamp_level:
        state: on
        brightness: 20
      light.caitlin_lamp_level:
        state: on
        brightness: 20
      fan.master_fan_level:
        state: on
        speed: high

  - name: Watch TV Living room
    entities:
      switch.dining_room_switch:
        state: off
      light.kitchen_level:
        state: on
        brightness: 10
      light.guest_hall_level:
        state: off
      light.master_hall_level:
        state: off
      light.powder_hall_level:
        state: off
      switch.main_hallway_switch:
        state: off
      light.living_room_level:
        state: off
      switch.living_room_outlet_switch:
        state: off

  - name: Watch TV Bedroom
    entities:
      light.mario_lamp_level:
        state: on
        brightness: 30
      light.caitlin_lamp_level:
        state: off
      switch.master_light_switch:
        state: off

  - name: Night Light
    entities:
      light.kitchen_level:
        state: on
        brightness: 5
      switch.porch:
        state: off
      light.powder_hall_level:
        state: off
      light.guest_hall_level:
        state: off
      light.master_hall_level:
        state: off
      switch.living_room_outlet_switch:
        state: off
      switch.outdoor_christmas_lights_switch:
        state: off

  - name: Morning
    entities:
      light.mario_lamp_level:
        state: on
        brightness: 20
      light.caitlin_lamp_level:
        state: on
        brightness: 100
      light.kitchen_level:
        state: on
        brightness: 100
      switch.main_hallway_switch:
        state: on
      light.guest_hall_level:
        state: on
        brightness: 100
      switch.living_room_outlet_switch:
        state: on

  - name: Dark
    entities:
      light.mario_lamp_level:
        state: off
      light.caitlin_lamp_level:
        state: off
      switch.master_light_switch:
        state: off
      switch.porch_switch:
        state: off
      switch.dining_room_switch:
        state: off
      light.kitchen_level:
        state: off
      light.guest_hall_level:
        state: off
      light.master_hall_level:
        state: off
      light.powder_hall_level:
        state: off
      switch.main_hallway_switch:
        state: off
      light.living_room_level:
        state: off
      switch.james_switch:
        state: off
      switch.office_switch:
        state: off
      switch.living_room_outlet_switch:
        state: off
      switch.outdoor_christmas_lights_switch:
        state: off

  - name: Dusk
    entities:
      switch.dining_room_switch:
        state: on
      light.guest_hall_level:
        state: on
        brightness: 255
      light.master_hall_level:
        state: on
        brightness: 255
      light.powder_hall_level:
        state: on
        brightness: 255
      light.kitchen_level:
        state: on
        brightness: 255
      switch.living_room_outlet_switch:
        state: on
      switch.outdoor_christmas_lights_switch:
        state: on

script:
  timed_guest_hallway:
    alias: "Turn on guest hallway and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_guest_hallway_off
      - service: homeassistant.turn_on
        data:
          entity_id: light.guest_hall_level
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_guest_hallway_off

  timer_guest_hallway_off:
    alias: "Turn off hallway after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - service: homeassistant.turn_off
        data:
          entity_id: light.guest_hall_level

  timed_master_hallway:
    alias: "Turn on master hallway and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_master_hallway_off
      - service: homeassistant.turn_on
        data:
          entity_id: light.master_hall_level
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_master_hallway_off

  timer_master_hallway_off:
    alias: "Turn off hallway after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: homeassistant.turn_off
        data:
          entity_id: light.master_hall_level

  timed_garage:
    alias: "Turn on garage and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_garage_off
      - service: homeassistant.turn_on
        data:
          entity_id: light.garage_level
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_garage_off

  timer_garage_off:
    alias: "Turn off garage after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: homeassistant.turn_off
        data:
          entity_id: light.garage_level

  timed_patio:
    alias: "Turn on patio and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_patio_off
      - service: homeassistant.turn_on
        data:
          entity_id: switch.patio_switch
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_patio_off

  timer_patio_off:
    alias: "Turn off patio after 7 minutes"
    sequence:
      - delay:
          minutes: 7
      - service: homeassistant.turn_off
        data:
          entity_id: switch.patio_switch

automation: !include automations.yaml

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion
  - platform: mqtt
    state_topic: "home-assistant/camera/motion"

alexa:

intent_script:
  ByeByeIntent:
    action:
      service: scene.turn_on
      entity_id: scene.dark
    speech:
      type: plain
      text: Bye Bye
  GoodMorningIntent:
    action:
      service: scene.turn_on
      entity_id: scene.dusk
    speech:
      type: plain
      text: !include alexa_confirm.yaml
  GoodNightIntent:
    action:
      service: scene.turn_on
      entity_id: scene.dark
    speech:
      type: plain
      text: !include alexa_confirm.yaml
  MuteIntent:
    action:
      service: remote.send_command
      data_template:
        command: Mute
        #yamaha receiver
        device: 29753204
        entity_id: remote.living_room
    speech:
      type: plain
      text: As you insist
  PlayIntent:
    action:
      service: remote.send_command
      data_template:
        command: Play
        #nexus player
        device: 37662777
        entity_id: remote.living_room
    speech:
      type: plain
      text: giggety

  PauseIntent:
    action:
      service: remote.send_command
      data_template:
        command: Pause
        #nexus player
        device: 37662777
        entity_id: remote.living_room
    speech:
      type: plain
      text: Darn straight


camera:
  - platform: foscam
    ip: !secret james_foscam_ip
    username: !secret james_foscam_username
    password: !secret james_foscam_password
    name: james_camera
  - platform: foscam
    ip: !secret javier_foscam_ip
    username: !secret javier_foscam_username
    password: !secret javier_foscam_password
    name: javier_camera
  - platform: ring

shell_command:
  foscam_location_jackie: '~/.homeassistant/scripts/set_foscam_location.sh jackie'
  foscam_location_couch: '~/.homeassistant/scripts/set_foscam_location.sh couch'
  foscam_location_dining: '~/.homeassistant/scripts/set_foscam_location.sh dining'

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

media_player:
  - platform: tts_bluetooth_speaker
    address: !secret echo_bluetooth_address
    volume: 0.8
    cache_dir: /tmp/tts

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1

input_boolean:
  override_home:
   name: Overrides home detection
   initial: off
   icon: mdi:toggle-switch

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
    - switch
    - light

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

#not yet ready
#cloud:
