homeassistant:
  name: Limonciello House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  # api_password: !secret api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#################
#Nest thermostat#
#################
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
climate:
  platform: nest
sensor:
  - platform: nest
    monitored_conditions:
      - 'humidity'
      - 'weather_temperature'
      - 'weather_humidity'
      - 'weather_condition'

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.1/24
#    home_interval: 10

#########
#Harmony#
#########
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.7
    activity: 21240104

group: !include group.yaml


#anova:
#  mac: 5C:31:3E:5D:E6:6A

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/
  autoheal: false

#for turning on echo support to zwave stuff
emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch

scene:
  - name: Bedroom dimmed
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 30
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 30
      light.hallway_a_level_4_0:
        state: off
      light.hallway_b_level_5_0:
        state: off
      light.hallway_c_level_8_0:
        state: off
      light.hallway_d_level_7_0:
        state: off

  - name: Bedroom normal
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 255
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 255

  - name: Dark
    entities:
      light.mario_lamp_level_2_0:
        state: off
      light.caitlin_lamp_level_3_0:
        state: off
      light.hallway_a_level_4_0:
        state: off
      light.hallway_b_level_5_0:
        state: off
      light.hallway_c_level_8_0:
        state: off
      light.hallway_d_level_7_0:
        state: off

  - name: Dusk
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 255
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 255
      light.hallway_a_level_4_0:
        state: on
        brightness: 255
      light.hallway_b_level_5_0:
        state: on
        brightness: 255
      light.hallway_c_level_8_0:
        state: on
        brightness: 255
      light.hallway_d_level_7_0:
        state: on
        brightness: 255
script:
  timed_hallway:
    alias: "Turn on hallway and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_off
      - service: homeassistant.turn_on
        data:
          entity_id: group.hallway
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_off

  timer_off:
    alias: "Turn off hallway after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - service: homeassistant.turn_off
        data:
          entity_id: group.hallway

automation: !include automation.yaml
