homeassistant:
  name: Limonciello House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#################
#Nest thermostat#
#################
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
climate:
  - platform: nest

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.1/24
#    home_interval: 10


##################
#weather tracking#
##################
sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather
      - temp_f
      - feelslike_string
      - relative_humidity
      - wind_string
      - heat_index_string

#########
#Harmony#
#########
#remote:
#  - platform: harmony
#    name: Living Room
#    host: 192.168.1.7
#    activity: 21240104

group: !include group.yaml


#anova:
#  mac: 5C:31:3E:5D:E6:6A

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config/
  autoheal: false

#for turning on echo support to zwave stuff
emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
    - switch

scene:
  - name: Bedroom dimmed
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 30
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 30

  - name: Bedroom normal
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 255
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 255

  - name: Dark
    entities:
      light.mario_lamp_level_2_0:
        state: off
      light.caitlin_lamp_level_3_0:
        state: off

  - name: Dusk
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 255
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 255

automation: !include automation.yaml

alexa:
  intents:
    MuteIntent:
      action:
        service: remote.send_command
        data_template:
          command: Mute
          #yamaha receiver
          device: 29753204
          entity_id: remote.living_room
      speech:
        type: plaintext
        text: As you insist
    PlayIntent:
      action:
        service: remote.send_command
        data_template:
          command: Play
          #nexus player
          device: 37662777
          entity_id: remote.living_room
      speech:
        type: plaintext
        text: giggety

    PauseIntent:
      action:
        service: remote.send_command
        data_template:
          command: Pause
          #nexus player
          device: 37662777
          entity_id: remote.living_room
      speech:
        type: plaintext
        text: Darn straight

