homeassistant:
  name: Limonciello House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path

notify:
  platform: html5
  gcm_api_key: !secret gcm_sender_key
  gcm_sender_id: !secret gcm_sender_id

config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

recorder:
  purge_days: 5
  exclude:
    domains:
      - updater
    entities:
      - sun.sun
      - sensor.pws_feelslike_string
      - sensor.pws_heat_index_string
      - sensor.pws_relative_humidity
      - sensor.pws_temp_f
      - sensor.pws_weather
      - sensor.pws_wind_string

#################
#Nest thermostat#
#################
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
climate:
  - platform: nest

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.1/24
#    home_interval: 10

#device_tracker:
#  - platform: bluetooth_le_tracker

##################
#weather tracking and hand built sensors#
##################
sensor:
  - platform: wunderground
    api_key: !secret wunderground_key
    monitored_conditions:
      - weather
      - temp_f
      - feelslike_string
      - relative_humidity
      - wind_string
      - heat_index_string
  - platform: template
    sensors:
      garage_door:
        value_template: '{% if is_state("sensor.garage_door_alarm_level_17_1", "0") %}closed{% else %}open{% endif %}'
        entity_id: sensor.garage_door_alarm_level_17_1
        friendly_name: 'Garage Door status'
      garage_house_door:
        value_template: '{% if is_state("sensor.garage_house_door_alarm_level_18_1", "0") %}closed{% else %}open{% endif %}'
        friendly_name: 'Garage/House Door status'
        entity_id: sensor.garage_house_door_alarm_level_18_1
      patio_door:
        value_template: '{% if is_state("sensor.patio_door_alarm_level_19_1", "0") %}closed{% else %}open{% endif %}'
        friendly_name: 'Patio Door status'
        entity_id: sensor.patio_door_alarm_level_19_1
      refrigerator_door:
        value_template: '{% if is_state("sensor.refrigerator_alarm_level_22_1", "0") %}closed{% else %}open{% endif %}'
        friendly_name: 'Refrigerator status'
        entity_id: sensor.refrigerator_alarm_level_22_1
      guest_motion:
        value_template: '{% if is_state("sensor.hallway_motion_alarm_level_9_1", "0") %}none{% else %}motion{% endif %}'
        friendly_name: 'Guest Hallway Motion status'
        entity_id: sensor.hallway_motion_alarm_level_9_1
      kitchen_motion:
        value_template: '{% if is_state("sensor.kitchen_motion_alarm_level_21_1", "0") %}none{% else %}motion{% endif %}'
        friendly_name: 'Kitchen Motion status'
        entity_id: sensor.kitchen_motion_alarm_level_21_1

#########
#Harmony#
#########
#remote:
#  - platform: harmony
#    name: Living Room
#    host: 192.168.1.7
#    activity: 21240104

group: !include groups.yaml


#anova:
#  mac: 5C:31:3E:5D:E6:6A

zwave:
  usb_path: /dev/ttyACM0
  config_path: /home/homeassistant/.homeassistant/config
  autoheal: false
  device_config: !include zwave_device_config.yaml

#for turning on echo support to zwave stuff
emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - light
    - switch

scene:
  - name: Watch TV Bedroom
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 30
      light.caitlin_lamp_level_3_0:
        state: off
      switch.master_light_switch_12_0:
        state: off

  - name: Night Light
    entities:
      light.kitchen_level_20_0:
        state: on
        brightness: 5
      switch.porch:
        state: off
      light.powder_hall_level_7_0:
        state: off
      light.guest_hall_level_4_0:
        state: on
        brightness: 5
      light.master_hall_level_8_0:
        state: off

  - name: Dark
    entities:
      light.mario_lamp_level_2_0:
        state: off
      light.caitlin_lamp_level_3_0:
        state: off
      switch.master_light_switch_12_0:
        state: off
      switch.porch_switch_13_0:
        state: off
      switch.dining_room_switch_14_0:
        state: off
      light.kitchen_level_20_0:
        state: off
      light.guest_hall_level_4_0:
        state: off
      light.master_hall_level_8_0:
        state: off
      light.powder_hall_level_7_0:
        state: off
      switch.main_hallway_switch_16_0:
        state: off
      light.living_room_level_15_0:
        state: off

  - name: Dusk
    entities:
      light.mario_lamp_level_2_0:
        state: on
        brightness: 255
      light.caitlin_lamp_level_3_0:
        state: on
        brightness: 255
      switch.dining_room_switch_14_0:
        state: on
      light.guest_hall_level_4_0:
        state: on
        brightness: 255
      light.master_hall_level_8_0:
        state: on
        brightness: 255
      light.powder_hall_level_7_0:
        state: on
        brightness: 255

script:
  timed_guest_hallway:
    alias: "Turn on guest hallway and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_guest_hallway_off
      - service: homeassistant.turn_on
        data:
          entity_id: light.guest_hall_level_4_0
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_guest_hallway_off

  timer_guest_hallway_off:
    alias: "Turn off hallway after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - service: homeassistant.turn_off
        data:
          entity_id: light.guest_hall_level_4_0

  timed_master_hallway:
    alias: "Turn on master hallway and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_master_hallway_off
      - service: homeassistant.turn_on
        data:
          entity_id: light.master_hall_level_8_0
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_master_hallway_off

  timer_master_hallway_off:
    alias: "Turn off hallway after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: homeassistant.turn_off
        data:
          entity_id: light.master_hall_level_8_0

  timed_garage:
    alias: "Turn on garage and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_garage_off
      - service: homeassistant.turn_on
        data:
          entity_id: light.garage_level_5_0
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_garage_off

  timer_garage_off:
    alias: "Turn off garage after 5 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: homeassistant.turn_off
        data:
          entity_id: light.garage_level_5_0

  timed_patio:
    alias: "Turn on patio and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_patio_off
      - service: homeassistant.turn_on
        data:
          entity_id: switch.patio_switch_13_0
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_patio_off

  timer_patio_off:
    alias: "Turn off patio after 7 minutes"
    sequence:
      - delay:
          minutes: 7
      - service: homeassistant.turn_off
        data:
          entity_id: switch.patio_switch_13_0

automation: !include automation.yaml

ring:
  username: !secret ring_username
  password: !secret ring_password

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

alexa:
  intents:
    ByeByeIntent:
      action:
        service: scene.turn_on
        entity_id: scene.dark
      speech:
        type: plaintext
        text: Bye Bye
    GoodMorningIntent:
      action:
        service: scene.turn_on
        entity_id: scene.dusk
      speech:
        type: plaintext
        text: !include alexa_confirm.yaml
    GoodNightIntent:
      action:
        service: scene.turn_on
        entity_id: scene.dark
      speech:
        type: plaintext
        text: !include alexa_confirm.yaml
    MuteIntent:
      action:
        service: remote.send_command
        data_template:
          command: Mute
          #yamaha receiver
          device: 29753204
          entity_id: remote.living_room
      speech:
        type: plaintext
        text: As you insist
    PlayIntent:
      action:
        service: remote.send_command
        data_template:
          command: Play
          #nexus player
          device: 37662777
          entity_id: remote.living_room
      speech:
        type: plaintext
        text: giggety

    PauseIntent:
      action:
        service: remote.send_command
        data_template:
          command: Pause
          #nexus player
          device: 37662777
          entity_id: remote.living_room
      speech:
        type: plaintext
        text: Darn straight


