light.mario_lamp_level:
  refresh_value: true
  polling_intensity: 1
  ignored: false
light.caitlin_lamp_level:
  refresh_value: true
  polling_intensity: 1
  ignored: false
light.guest_hall_level:
  refresh_value: true
  polling_intensity: 1
  ignored: false
light.garage_level:
  refresh_value: true
  polling_intensity: 1
  ignored: false
light.powder_hall_level:
  refresh_value: true
  polling_intensity: 1
  ignored: false
switch.outdoor_christmas_lights_switch:
  ignored: true
light.kitchen_level:
  ignored: false
  polling_intensity: 1
switch.patio_switch:
  ignored: false
  polling_intensity: 1
light.living_room_level:
  ignored: false
  polling_intensity: 1
switch.main_hallway_switch:
  ignored: false
  polling_intensity: 1
switch.dining_room_switch:
  ignored: false
  polling_intensity: 1
